fix: new-1

diff --git a/.github/workflows/build-multi-sast-prod.yml b/.github/workflows/build-multi-sast-prod.yml
--- a/.github/workflows/build-multi-sast-prod.yml
+++ b/.github/workflows/build-multi-sast-prod.yml
@@ -2,11 +2,6 @@ name: Build Multi-Sast-Platform Prod
 
 on:
     workflow_dispatch:
-        inputs:
-            version:
-                description: "Input version (e.g. x.x.x-月日)"
-                required: true
-                type: string
 
 jobs:
     build_yakit:
@@ -21,6 +16,16 @@ jobs:
             CERT_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
 
         steps:
+            - name: Check if the version number is correct
+              run: |
+                  VERSION_INPUT=$GITHUB_REF_NAME
+                  if [[ $VERSION_INPUT !=~ ^v.*-sast$ ]]; then
+                    echo "Error: Version must start with 'v' and end with '-sast'." >&2
+                    exit 1
+                  else
+                    echo "Version starts with 'v': $VERSION_INPUT"
+                  fi
+
             - uses: actions/checkout@v4
             - uses: actions/setup-node@v4
               with:
@@ -79,8 +84,10 @@ jobs:
 
             - name: Echo SastScan Package Version To Env
               run: |
-                ENV_TAG=${{ github.event.inputs.version }}
-                echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
+                  ENV_TAG=${{ GITHUB_REF_NAME }}
+                  ENV_TAG=${ENV_TAG#v}
+                  ENV_TAG=${ENV_TAG%-sast}
+                  echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
               shell: bash
 
             - run: yarn install
@@ -152,7 +159,11 @@ jobs:
     #     runs-on: ubuntu-latest
     #     steps:
     #         - name: Echo Package Version To Env
-    #           run: echo "ENV_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
+    #           run: |
+    #               ENV_TAG=${{ GITHUB_REF_NAME }}
+    #               ENV_TAG=${ENV_TAG#v}
+    #               ENV_TAG=${ENV_TAG%-sast}
+    #               echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
 
     #         - name: Download SastScan And Legacy SastScan
     #           uses: actions/download-artifact@v4
