feat: yakit接入矩阵打包

diff --git a/.github/workflows/build-multi-irify-prod.yml b/.github/workflows/build-multi-irify-prod.yml
--- a/.github/workflows/build-multi-irify-prod.yml
+++ b/.github/workflows/build-multi-irify-prod.yml
@@ -7,114 +7,114 @@ on:
 
 jobs:
     prepare_engine:
-      runs-on: macos-15
+        runs-on: macos-15
 
-      outputs:
-        engine_version: ${{ steps.engine_ver.outputs.version }}
-      steps:
-        - uses: actions/checkout@v4
+        outputs:
+            engine_version: ${{ steps.engine_ver.outputs.version }}
+        steps:
+            - uses: actions/checkout@v4
 
-        - name: Check if the version number is correct
-          run: |
-            VERSION_INPUT=$GITHUB_REF_NAME
-            if [[ $VERSION_INPUT != v*-irify ]]; then
-              echo "Error: Version must start with 'v' and end with '-irify'." >&2
-              exit 1
-            else
-              echo "Version starts with 'v': $VERSION_INPUT"
-            fi
+            - name: Check if the version number is correct
+              run: |
+                  VERSION_INPUT=$GITHUB_REF_NAME
+                  if [[ $VERSION_INPUT != v*-irify ]]; then
+                    echo "Error: Version must start with 'v' and end with '-irify'." >&2
+                    exit 1
+                  else
+                    echo "Version starts with 'v': $VERSION_INPUT"
+                  fi
 
-        - name: Fetch Latest Engine Version And Set To Env
-          id: engine_ver
-          run: |
-            mkdir -p bins
-            wget -O bins/engine-version.txt https://yaklang.oss-accelerate.aliyuncs.com/yak/latest/version.txt
-            cat bins/engine-version.txt
-            YAK_VERSION=$(cat bins/engine-version.txt | tr -d '\n')
-            echo "ENGINE_VERSION=$YAK_VERSION" >> $GITHUB_ENV
-            echo "version=$YAK_VERSION" >> $GITHUB_OUTPUT
-        # ENGINE_VERSION 给shell 用(wget / script)
-        # version 给cache / job outputs 用(关键)
+            - name: Fetch Latest Engine Version And Set To Env
+              id: engine_ver
+              run: |
+                  mkdir -p bins
+                  wget -O bins/engine-version.txt https://yaklang.oss-accelerate.aliyuncs.com/yak/latest/version.txt
+                  cat bins/engine-version.txt
+                  YAK_VERSION=$(cat bins/engine-version.txt | tr -d '\n')
+                  echo "ENGINE_VERSION=$YAK_VERSION" >> $GITHUB_ENV
+                  echo "version=$YAK_VERSION" >> $GITHUB_OUTPUT
+            # ENGINE_VERSION 给shell 用(wget / script)
+            # version 给cache / job outputs 用(关键)
 
-        - name: Restore Yak Engine Cache
-          uses: actions/cache@v4
-          with:
-            path: bins
-            key: macos-yak-engine-${{ steps.engine_ver.outputs.version }}
+            - name: Restore Yak Engine Cache
+              uses: actions/cache@v4
+              with:
+                  path: bins
+                  key: macos-yak-engine-${{ steps.engine_ver.outputs.version }}
 
-      # ---------- Linux ----------
-        - name: Download Yak Engine (Linux)
-          run: |
-            if [ ! -f bins/yak_linux_amd64.zip ]; then
-              wget -O bins/yak_linux_amd64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_linux_amd64
-              zip bins/yak_linux_amd64.zip bins/yak_linux_amd64
-              rm bins/yak_linux_amd64
-            fi
+            # ---------- Linux ----------
+            - name: Download Yak Engine (Linux)
+              run: |
+                  if [ ! -f bins/yak_linux_amd64.zip ]; then
+                    wget -O bins/yak_linux_amd64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_linux_amd64
+                    zip bins/yak_linux_amd64.zip bins/yak_linux_amd64
+                    rm bins/yak_linux_amd64
+                  fi
 
-        - name: Download Yak Engine (Linux-arm64)
-          run: |
-            if [ ! -f bins/yak_linux_arm64.zip ]; then
-              wget -O bins/yak_linux_arm64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_linux_arm64
-              zip bins/yak_linux_arm64.zip bins/yak_linux_arm64
-              rm bins/yak_linux_arm64
-            fi
+            - name: Download Yak Engine (Linux-arm64)
+              run: |
+                  if [ ! -f bins/yak_linux_arm64.zip ]; then
+                    wget -O bins/yak_linux_arm64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_linux_arm64
+                    zip bins/yak_linux_arm64.zip bins/yak_linux_arm64
+                    rm bins/yak_linux_arm64
+                  fi
 
-        # ---------- Windows ----------
-        - name: Download Yak Engine (Windows)
-          run: |
-            if [ ! -f bins/yak_windows_normal_amd64.zip ]; then
-              wget -O bins/yak_windows_amd64.exe https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_windows_amd64.exe
-              zip bins/yak_windows_normal_amd64.zip bins/yak_windows_amd64.exe
-              rm bins/yak_windows_amd64.exe
-            fi
+            # ---------- Windows ----------
+            - name: Download Yak Engine (Windows)
+              run: |
+                  if [ ! -f bins/yak_windows_normal_amd64.zip ]; then
+                    wget -O bins/yak_windows_amd64.exe https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_windows_amd64.exe
+                    zip bins/yak_windows_normal_amd64.zip bins/yak_windows_amd64.exe
+                    rm bins/yak_windows_amd64.exe
+                  fi
 
-        - name: Download Yak Legacy Engine (Windows)
-          run: |
-            if [ ! -f bins/yak_windows_legacy_amd64.zip ]; then
-              wget -O bins/yak_windows_amd64.exe https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_windows_legacy_amd64.exe
-              zip bins/yak_windows_legacy_amd64.zip bins/yak_windows_amd64.exe
-              rm bins/yak_windows_amd64.exe
-            fi
+            - name: Download Yak Legacy Engine (Windows)
+              run: |
+                  if [ ! -f bins/yak_windows_legacy_amd64.zip ]; then
+                    wget -O bins/yak_windows_amd64.exe https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_windows_legacy_amd64.exe
+                    zip bins/yak_windows_legacy_amd64.zip bins/yak_windows_amd64.exe
+                    rm bins/yak_windows_amd64.exe
+                  fi
 
-      # ---------- macOS ----------
-        - name: Download Yak Engine (macOS)
-          run: |
-            if [ ! -f bins/yak_darwin_amd64 ]; then
-              wget -O bins/yak_darwin_amd64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_amd64
-            fi
+            # ---------- macOS ----------
+            - name: Download Yak Engine (macOS)
+              run: |
+                  if [ ! -f bins/yak_darwin_amd64 ]; then
+                    wget -O bins/yak_darwin_amd64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_amd64
+                  fi
 
-        - name: Download Yak Engine (macOS-arm64)
-          run: |
-            if [ ! -f bins/yak_darwin_arm64 ]; then
-              wget -O bins/yak_darwin_arm64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_arm64
-            fi
+            - name: Download Yak Engine (macOS-arm64)
+              run: |
+                  if [ ! -f bins/yak_darwin_arm64 ]; then
+                    wget -O bins/yak_darwin_arm64 https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_arm64
+                  fi
 
-        - name: Signature Mac Engine
-          run: chmod +x ./packageScript/script/signature.sh && ./packageScript/script/signature.sh
+            - name: Signature Mac Engine
+              run: chmod +x ./packageScript/script/signature.sh && ./packageScript/script/signature.sh
 
-        - name: Fetch macOS sha256
-          run: |
-            wget -O bins/yak_darwin_amd64.sha256.txt https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_amd64.sha256.txt
-            wget -O bins/yak_darwin_arm64.sha256.txt https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_arm64.sha256.txt
+            - name: Fetch macOS sha256
+              run: |
+                  wget -O bins/yak_darwin_amd64.sha256.txt https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_amd64.sha256.txt
+                  wget -O bins/yak_darwin_arm64.sha256.txt https://yaklang.oss-accelerate.aliyuncs.com/yak/${ENGINE_VERSION}/yak_darwin_arm64.sha256.txt
 
-        - name: Upload Yak Engine Artifact
-          uses: actions/upload-artifact@v4
-          with:
-            name: yak-engine
-            path: bins
-            retention-days: 1
+            - name: Upload Yak Engine Artifact
+              uses: actions/upload-artifact@v4
+              with:
+                  name: yak-engine
+                  path: bins
+                  retention-days: 1
 
     build_yakit:
         needs: prepare_engine
         runs-on: macos-15
         strategy:
-          fail-fast: false
-          matrix:
-            include:
-              - version: irify
-                artifact_name: IRify
-              - version: irifyee
-                artifact_name: IRifyEnpriTrace
+            fail-fast: false
+            matrix:
+                include:
+                    - version: irify
+                      artifact_name: IRify
+                    - version: irifyee
+                      artifact_name: IRifyEnpriTrace
         env:
             CI: ""
             NODE_OPTIONS: --max_old_space_size=4096
@@ -134,8 +134,8 @@ jobs:
             - name: Download Yak Engine Artifact
               uses: actions/download-artifact@v4
               with:
-                name: yak-engine
-                path: bins
+                  name: yak-engine
+                  path: bins
 
             - run: echo ${{ github.ref_name }}
             - run: cp buildutil/zip /usr/local/bin/zip
@@ -180,30 +180,81 @@ jobs:
                   # Yakit            -1.3.4-sp6-darwin-arm64(.dmg|.exe|.AppImage)
 
             - name: Check build output
-              run: |
-                if [ "${{ matrix.version }}" = "irify" ]; then
-                  ./packageScript/script/check-build-package.sh IRify
-                else
-                  ./packageScript/script/check-build-package.sh IRifyEnpriTrace
-                fi
+              run: ./packageScript/script/check-build-package.sh ${{ matrix.artifact_name }}
               shell: bash
 
             - name: Upload ${{ matrix.artifact_name }} Artifacts
               uses: actions/upload-artifact@v4
               with:
-                name: ${{ matrix.artifact_name }}-artifacts
-                path: |
-                  ./release/*-${{ env.ENV_TAG }}-*.exe
-                  ./release/*-${{ env.ENV_TAG }}-*.dmg
-                  ./release/*-${{ env.ENV_TAG }}-*.AppImage
-                if-no-files-found: error
-                retention-days: 1
+                  name: ${{ matrix.artifact_name }}-artifacts
+                  path: |
+                      ./release/*-${{ env.ENV_TAG }}-*.exe
+                      ./release/*-${{ env.ENV_TAG }}-*.dmg
+                      ./release/*-${{ env.ENV_TAG }}-*.AppImage
+                  if-no-files-found: error
+                  retention-days: 1
 
     cleanup_engine_artifact:
-      needs: build_yakit
-      runs-on: ubuntu-latest
-      steps:
-        - name: Delete yak-engine artifact
-          uses: geekyeggo/delete-artifact@v5
-          with:
-            name: yak-engine
+        needs: build_yakit
+        runs-on: ubuntu-latest
+        steps:
+            - name: Delete yak-engine artifact
+              uses: geekyeggo/delete-artifact@v5
+              with:
+                  name: yak-engine
+
+    # publish_software_to_oss:
+    #     needs:
+    #         - build_yakit
+    #     strategy:
+    #         matrix:
+    #             artifact: [IRify, IRifyEnpriTrace] # 需要发布的软件名前缀
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #         - name: Echo Package Version To Env
+    #           run: |
+    #               ENV_TAG=${{ github.ref_name }}
+    #               ENV_TAG=${ENV_TAG#v}
+    #               ENV_TAG=${ENV_TAG%-irify}
+    #               echo "ENV_TAG=$ENV_TAG" >> $GITHUB_ENV
+
+    #         - name: Download IRify And Legacy IRify
+    #           uses: actions/download-artifact@v4
+    #           with:
+    #               name: ${{ matrix.artifact }}-artifacts
+    #               merge-multiple: true
+
+    #         - run: ls
+    #           name: Ls Published Artifacts...
+
+    #         - name: Create Release and Upload Assets
+    #           if: ${{ matrix.artifact == 'IRify' }}
+    #           uses: ncipollo/release-action@v1
+    #           with:
+    #               artifacts: ./*
+    #               token: ${{ secrets.GITHUB_TOKEN }}
+    #               name: Release ${{ github.ref_name }}
+    #               tag: ${{ github.ref_name }}
+
+    #         - name: Generate OSS File Path
+    #           run: |
+    #               if [ "${{ matrix.artifact }}" = "IRify" ]; then
+    #                 echo "FILE_PATH=irify" >> $GITHUB_ENV
+    #               elif [ "${{ matrix.artifact }}" = "IRifyEnpriTrace" ]; then
+    #                 echo "FILE_PATH=svip" >> $GITHUB_ENV
+    #               else
+    #                 echo "No corresponding file path" >&2
+    #                 exit 1
+    #               fi
+    #         - name: Show ENV.FILE_PATH
+    #           run: echo "FILE_PATH： $FILE_PATH"
+
+    #         - name: Upload IRify To OSS
+    #           uses: tvrcgo/upload-to-oss@master
+    #           with:
+    #               key-id: ${{ secrets.OSS_KEY_ID }}
+    #               key-secret: ${{ secrets.OSS_KEY_SECRET }}
+    #               region: oss-accelerate
+    #               bucket: yaklang
+    #               assets: |
+    #                   *:/${{ env.FILE_PATH }}/${{ env.ENV_TAG }}/
